save_dir  : './checkpoints/'
log_dir : './log/'
# seed: [0,2001,2023,1,42]
seed: [0]
extractor: {'type':'GAT'}
total_timesteps: 2e4
Model: ['Graph_MaskablePPO']
# Env: ['PLDriving_highway_v2_Kinematic','PLDriving_highway_v2_Graph','PLDriving_highway_v2_OccupancyGrid']
Env: ['PLDriving_highway_v2_Graph']

Envs:
  PLDriving_highway_v1_Kinematic:
    n_actions: 3
    max_speed: 40
    single_step: 1
    w_speed: 0.8
    w_p_time: 0.1
    w_p_crash: 100
    w_p_lc: 0.1
    highway_lanes: 3

  PLDriving_highway_v1_Graph:
    n_actions: 3
    max_speed: 40
    single_step: 1
    w_speed: 0.8
    w_p_time: 0.1
    w_p_crash: 100
    w_p_lc: 0.1
    highway_lanes: 3
    sense_dist: 100

  PLDriving_highway_v1_RuleBased:
    n_actions: 3
    max_speed: 40
    single_step: 1
    w_speed: 0.8
    w_p_time: 0.1
    w_p_crash: 100
    w_p_lc: 0.1
    highway_lanes: 3
    auto: False
    collaborative_lc: True

  PLDriving_highway_v1_OccupancyGrid:
    n_actions: 3
    max_speed: 40
    single_step: 1
    w_speed: 0.8
    w_p_time: 0.1
    w_p_crash: 100
    w_p_lc: 0.1
    highway_lanes: 3
    grid_size: [[0,2200],[-9,0]] #  the whole road network
    grid_step: [5,3] # same as length of vehicle

  PLDriving_highway_v2_Kinematic:
    n_actions: 3
    max_speed: 40
    single_step: 1
    w_speed: 1
    w_p_time: 0.1
    w_p_crash: 100
    w_p_lc: 0.1
    highway_lanes: 4
    hdv_interval: 2
    lc_mode: simultaneous

  PLDriving_highway_v2_Graph:
    n_actions: 3
    max_speed: 40
    single_step: 1
    w_speed: 1
    w_p_time: 0.3
    w_p_crash: 100
    w_p_lc: 0.1
    highway_lanes: 4
    sense_dist: 100
    hdv_interval: 2
    safe_monitor: True
    lc_mode: 'sequential'

  PLDriving_highway_v2_OccupancyGrid:
    n_actions: 3
    max_speed: 40
    single_step: 1
    w_speed: 1
    w_p_time: 0.1
    w_p_crash: 100
    w_p_lc: 0.1
    highway_lanes: 4
    grid_size: [[0,2200],[-12,0]] #  the whole road network
    grid_step: [5,3] # same as length of vehicle
    hdv_interval: 2
    lc_mode: 'sequential'

  PLDriving_highway_v2_RuleBased:
    n_actions: 3
    max_speed: 40
    single_step: 1
    w_speed: 1
    w_p_time: 0.1
    w_p_crash: 100
    w_p_lc: 1
    highway_lanes: 3
    auto: False
    collaborative_lc: True
    hdv_interval: 2
    lc_mode: None

  PLDriving_highway_v2_CoOP:
    n_actions: 3
    max_speed: 40
    single_step: 1
    w_speed: 1
    w_p_time: 0.1
    w_p_crash: 100
    w_p_lc: 0.1
    highway_lanes: 3
    hdv_interval: 2
    lc_mode: None

  PLDriving_highway_v2_LC2013:
    n_actions: 3
    max_speed: 40
    single_step: 1
    w_speed: 0.8
    w_p_time: 0.1
    w_p_crash: 100
    w_p_lc: 0.1
    highway_lanes: 4
    auto: True
    collaborative_lc: False
    hdv_interval: 2

  PLDriving_highway_v3_Graph:
    n_actions: 5
    max_speed: 40
    single_step: 1
    w_speed: 0.8
    w_p_time: 0.1
    w_p_crash: 100
    w_p_lc: 0.1
    highway_lanes: 4
    sense_dist: 20
    hdv_interval: 2


Models:
  MaskablePPO:
    batch_size: 64
    n_steps: 3000
    n_epochs: 5
    learning_rate: 0.0006
    gamma: 0.8
  Graph_MaskablePPO:
    batch_size: 64
    n_steps: 3000
    n_epochs: 5
    learning_rate: 0.0006
    gamma: 0.8
  A2C:
    normalize_advantage: True
    learning_rate: 0.0006
    # n_steps: 10
    gamma: 0.8
  DQN:
    learning_starts: 0
    batch_size: 64
    gamma: 0.8
    buffer_size: 100000
  DDQN:
    batch_size: 64
    # net_arch: [32,16]
    gamma: 0.8
    # target_update_interval: 2000
    # exploration_final_eps: 0.1
    buffer_size: 100000
  GCD3QN:
    batch_size: 128
    gamma: 0.8
    eps_dec: 0.0002