save_dir  : './checkpoints/'
log_dir : './log/'
seed: [0]
extractor: {'type':'GAT'}
total_timesteps: 2e4
Model: ['Graph_MaskablePPO']
Env: ['PLDriving_highway_CoOP']


Envs:
  PLDriving_highway_Kinematic:
    n_actions: 3
    max_speed: 40
    single_step: 1
    w_speed: 1
    w_p_time: 0.1
    w_p_crash: 100
    w_p_lc: 0.1
    highway_lanes: 4
    hdv_interval: 2
    lc_mode: 'sequential'
    safe_monitor: True

  PLDriving_highway_OccupancyGrid:
    n_actions: 3
    max_speed: 40
    single_step: 1
    w_speed: 1
    w_p_time: 0.1
    w_p_crash: 100
    w_p_lc: 0.1
    highway_lanes: 4
    hdv_interval: 2
    lc_mode: 'sequential'
    safe_monitor: True
    grid_size: [[0,2200],[-9,0]] #  the whole road network
    grid_step: [5,3] # same as length of vehicle

  PLDriving_highway_Graph:
    n_actions: 3
    max_speed: 40
    single_step: 1
    w_speed: 1
    w_p_time: 0.1
    w_p_crash: 100
    w_p_lc: 0.1
    highway_lanes: 4
    hdv_interval: 2
    lc_mode: 'sequential'
    safe_monitor: True
    sense_dist: 100

  PLDriving_highway_Plexe:
    n_actions: 3
    max_speed: 40
    single_step: 1
    w_speed: 1
    w_p_time: 0.1
    w_p_crash: 100
    w_p_lc: 0.1
    highway_lanes: 4
    hdv_interval: 2
    auto: False
    collaborative_lc: True
    lc_mode: None
    safe_monitor: None

  PLDriving_highway_CoOP:
    n_actions: 3
    max_speed: 40
    single_step: 1
    w_speed: 1
    w_p_time: 0.1
    w_p_crash: 100
    w_p_lc: 0.1
    highway_lanes: 4
    hdv_interval: 2
    lc_mode: None
    safe_monitor: True


Models:
  Graph_MaskablePPO:
    batch_size: 64
    n_steps: 3000
    n_epochs: 5
    learning_rate: 0.0006
    gamma: 0.8
  DDQN:
    batch_size: 64
    gamma: 0.8
    buffer_size: 100000
